### ISSUE TITLE
Book

### ISSUE THREAD

**Issue by onuagamer** [andreimarin90/VSDocs#21]
Nu merge view page : Oops! That page can''t be found.

**Comment by leonidrm** [comment]
CP "Books" nu are single page. Daca e nevoie se poate de adaugat (o sa fie nevoie de markup si stilizare )

**Comment by andreimarin90** [comment]
Din cate stiu nu ai voie sa ai un CP TYPE  care sa nu aiba single view. @toleabivol tu cum stii ca e?

**Comment by andreimarin90** [comment]
Timeout pana raspunde anatol @leonidrm

**Comment by andreimarin90** [comment]
@toleabivol reminder

**Comment by toleabivol** [comment]
Nu e nevoie sa aiba single , este si setting 'has_single'=>false .
