### ISSUE TITLE
Book featured image

### ISSUE THREAD

**Issue by onuagamer** [andreimarin90/VSDocs#23]
Poza apare cu un height foarte mare

**Comment by leonidrm** [comment]
Este nevoie de stilizare.

**Comment by andreimarin90** [comment]
Ma voi uita da nu cred. Codul imaginii presupune width si height trecut acolo inline foarte mare. Ma informez si te tin la curent. Disregard for now

**Comment by andreimarin90** [comment]
@leonidrm http://bigbangthemes.net/VSDocs_WP/book/ ? Var dumps lasate aiurea 	string(1) "#" LALALA int(551) int(564) int(566) int(568) int(567) 

Acum e pagina goala.

**Comment by andreimarin90** [comment]
@leonidrm fixed complet?

**Comment by leonidrm** [comment]
Am adaugat in functions.php aceste doua linii:
add_image_size( 'book_single', 840 , 810, true );
add_image_size( 'book_grid', 200 , 250, true );
respectiv s-a schimbat putin codul in "book-view.php"
Dupa parerea mea issue closed :) @andreimarin90
