### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by onuagamer** [andreimarin90/VSDocs#25]
E alt tip de tabel fata de cel din demo

**Comment by leonidrm** [comment]
Necesita stilizare.

**Comment by andreimarin90** [comment]
Sunt 2 types pe demo html. Disregard, fac eu.

**Comment by andreimarin90** [comment]
@leonidrm poti te rog sa faci tu? Sunt foarte backlogged si ma ajuta mult. Mersi!

**Comment by andreimarin90** [comment]
Trebuie sa lipseasca acel outside border

**Comment by andreimarin90** [comment]
@leonidrm cum a ramas cu asta?

**Comment by leonidrm** [comment]
@andreimarin90 Pe localhost am reprodus acel tabel, fiind identic cu cel din HTML
