### ISSUE TITLE
Steps with image

### ISSUE THREAD

**Issue by onuagamer** [andreimarin90/VSDocs#28]
Nu arata cum trebuie

**Comment by andreimarin90** [comment]
@leonidrm http://bigbangthemes.net/VSDocs_WP/steps-tabs/

**Comment by leonidrm** [comment]
markupul e respectat 100% precum si in varianta HTML. Presupun ceva issue cu js

**Comment by leonidrm** [comment]
Aceasta incurca :

.main-content img, .main-content div {
    max-width: 100%;
}

**Comment by toleabivol** [comment]
Cam des erori de genu asta ... :thought_balloon:
