### ISSUE TITLE
Modal autoclose

### ISSUE THREAD

**Issue by onuagamer** [andreimarin90/VSDocs#32]
Nu se inchide

**Comment by leonidrm** [comment]
Eu am verificat si totul lucreaza ok. @andreimarin90 verifica te rog si tu

**Comment by andreimarin90** [comment]
@leonidrm te rog reopen. Nu mai close pana nu imi dau si eu "sign off" atunci cand nu faci reparatii pls!

**Comment by leonidrm** [comment]
Totul e ok. Dupa ce am scris commentul de mai sus am gasit problema in "data-config=" options al pluginului. Am fixat eroarea si dupa care am inchis acest issue. Autoclose nu functiona cind era Modal "simple" type.
