### ISSUE TITLE
Button Page

### ISSUE THREAD

**Issue by onuagamer** [andreimarin90/VSDocs#42]
Alignment gresit fata de header ( cu sau fara col md 12)

**Comment by andreimarin90** [comment]
@leonidrm trebuie sa te uiti, nu imi dau seama ce e aici si nu cunosc markup cum il cunosti tu. Nu e la nivel partea din header cu contentul paginii. Vezi pe live. http://bigbangthemes.net/VSDocs_WP/buttons/ se intampla la mai multe pag.
