### ISSUE TITLE
Pages - Notification skip button

### ISSUE THREAD

**Issue by onuagamer** [andreimarin90/VSDocs#49]
Nu inchide nimic butonu skip
![screenshot_3](https://cloud.githubusercontent.com/assets/12714473/9809129/469bc370-586e-11e5-8cc9-e6c42bed1c17.jpg)

**Comment by leonidrm** [comment]
La buttonul "Skip" e necesar de adaugat clasa "js-close" prin optiunea "add_class" field. In caz de este o idee mai buna, eu sunt gata sa o implementez @andreimarin90

**Comment by andreimarin90** [comment]
trebuie sa fie o idee mai buna. Hai sa includem skip button in notificare daca e cumva. brainstorm it.

**Comment by andreimarin90** [comment]
@leonidrm
