### ISSUE TITLE
Code Highlight javascript

### ISSUE THREAD

**Issue by onuagamer** [andreimarin90/VSDocs#51]
</br> nu ar trebui sa se vada
si ce se poate face pentru indentare. Incearca sa-l faci sa arate bine daca se poate
![screenshot_5](https://cloud.githubusercontent.com/assets/12714473/9811502/579fee5a-5880-11e5-90be-f356ab295b85.jpg)

**Comment by leonidrm** [comment]
Aceeasi situatie precum e si la issue #15 (se vor rezolva concomitent)

**Comment by leonidrm** [comment]
@onuagamer @andreimarin90  Pentru identare trebuie ca "codeul" sa fie copiat direct dintr-un IDE si inserat in editorul Wordpress. Numai in asa caz se poate de pastrat identare. Acum shortcodul a fost fixat.
