### ISSUE TITLE
HTML pannel nu reusesc sa il reproduc

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/VSDocs#58]
http://bigbangthemes.net/VSDocs_WP/panels/

vs

http://themes.vsart.me/vsdocs/panels.html

**Comment by andreimarin90** [comment]
idem here http://bigbangthemes.net/VSDocs_WP/notification/

**Comment by leonidrm** [comment]
@andreimarin90 atrageti atentia cum am introdus markupul in editor
