### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/VSDocs#59]
1 singura categorie per view.

**Comment by leonidrm** [comment]
@andreimarin90 Ceva probleme cu permalinkurile
Pentru ca Mixed View type sa lucreze, CP Tutorials trebuie sa dispuna de o ierarhie de categorie Parent-> Child

**Comment by leonidrm** [comment]
@andreimarin90 coincidenta de page-slug si taxonomia CP. Acest lucru ducea la afisarea arhivei taxonomiei "tutorial"(pe archive.php) in loc de afisarea shortcodului (pe page.php). Am redenumit slugul paginii (tutorial -> tutorial-mix)
