### ISSUE TITLE
Tutorials - mixed views

### ISSUE THREAD

**Issue by onuagamer** [andreimarin90/VSDocs#63]
Nu arata nimic

**Comment by leonidrm** [comment]
@andreimarin90 Ceva probleme cu permalinkurile
Pentru ca Mixed View type sa lucreze, CP Tutorials trebuie sa dispuna de o ierarhie de categorie Parent-> Child

**Comment by andreimarin90** [comment]
Explica te rog. Trebuie sa avem unele categorii care sa indexeze altele?

**Comment by leonidrm** [comment]
@andreimarin90 
1.) Shortcodul extrage toate categoriile CP Tutorial. 
2.) Apoi alege categoriile de top (parrents "0").
3.) Pentru fiecare categorie de top se creaza cite o boxa aparte
4.) Boxele sunt suplinite cu posturile ce fac parte din categoriile "child" ale categoriei de baza a boxei

P.S. Ramificatiile pot sa fie de orice nivel (nu este limita)
